# an ini file is the cofiguration file for pytest. Used to customize and standarize the 
# behaviour of the pytesting framework. pythonpath = . is used to add the current directory to
# the python path so that pytest can find the modules to test 
# the markets = is used to define custom markers that can be used to mark and run specific tests

[pytest]
pythonpath = .
markers =
    integration: mark a test as an integration test.
    unit: mark a test as a unit test.